-- MySQL Script generated by MySQL Workbench
-- 07/22/16 04:28:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_created` DATETIME NOT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'Не выполнен',
  `client_name` VARCHAR(100) NOT NULL,
  `user_id` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `order_day`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `order_day` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `delivery_time` VARCHAR(45) NULL,
  `delivery_type` VARCHAR(45) NOT NULL DEFAULT 'Доставка',
  `city_id` INT NOT NULL,
  `street` VARCHAR(255) NULL,
  `building` VARCHAR(45) NULL,
  `room` VARCHAR(45) NULL,
  `client_comment` VARCHAR(255) NULL,
  `mannager_comment` VARCHAR(255) NULL,
  `delivery_date` DATE NOT NULL,
  `payment_type` VARCHAR(45) NOT NULL,
  `card_number` VARCHAR(100) NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `is_changed` TINYINT NOT NULL DEFAULT 0,
  `changed_by` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `order_day_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `order_day_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_day_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
